version: '3'

services:
    api:
        build: .
        command: ["./wait-for-it.sh", "db:5432", "-t", "0", "--",
                  "python", "manage.py", "runserver", "0.0.0.0:8080"]

        container_name: django_api

        volumes:
            - .:/code

        ports:
            - "8080:8080"

        depends_on:
            - db

    db:
        image: postgres

        container_name: postgres_db

        environment:
            - POSGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

        volumes:
            - ./data/db:/var/lib/postgresql/data

        ports:
            - 127.0.0.1:5432:5432
