# Generated by Django 3.2.4 on 2021-06-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('consult_date', models.DateField()),
                ('store_url', models.CharField(max_length=1000)),
                ('product_url', models.CharField(max_length=1000)),
                ('product_url_image', models.CharField(max_length=1000)),
                ('product_created_at', models.DateTimeField()),
            ],
        ),
    ]
